#!/bin/bash

PMS_LIB_DIR=/usr/lib/plexmediaserver
PMS_DOWNLOAD_DIR=/tmp/plex_tmp_download	

get_pms_build(){

	local cpuinfo=$(grep Features /proc/cpuinfo)
	if [[ $cpuinfo =~ .*neon.* ]] && [[ $cpuinfo =~ .*vfpv4.* ]] && [[ $cpuinfo =~ .*thumb.* ]] && [[ $cpuinfo =~ .*idiva.* ]]; then
		echo "netgear"		
	elif [[ $cpuinfo =~ .*neon.* ]]; then
		echo "synology_neon"
	else
		echo "synology"
	fi
}

install_netgear(){

	local PMS_URL='https://downloads.plex.tv/plex-media-server/0.9.16.6.1993-5089475/plexmediaserver-ros6-binaries-annapurna_0.9.16.6.1993-5089475_armel.deb'
	local PMS_HASH='675f0ac091ef5439eb519747b4359b119f7bb229fad9379ea221f7a8a578cb90'

	echo "Downloading readynas package ..."
	cd $PMS_DOWNLOAD_DIR	
	curl --progress-bar -o readynas.deb $PMS_URL

	local PMS_DOWNLOAD_HASH=`sha256sum readynas.deb | cut -d' ' -f1`

	if [ "$PMS_HASH" != "$PMS_DOWNLOAD_HASH" ]
	then
		echo "Checksum mismatch. Downloaded file does not match this package."
		exit 1
	else
		echo "Passed checksum test."
	fi

	echo "Extracting readynas.deb ..."
        ar p readynas.deb data.tar.gz | tar -xzf - -C $PMS_LIB_DIR/ --strip-components=4 ./apps/plexmediaserver-annapurna/Binaries

	# remove not used files
	rm $PMS_LIB_DIR/config.xml
	
}

install_synology(){

	local PMS_URL='https://downloads.plex.tv/plex-media-server/0.9.16.6.1993-5089475/PlexMediaServer-0.9.16.6.1993-5089475-arm7.spk'
	local PMS_HASH='dfe4fea0cf8aadd4d36d967e2013b64b5bbc461d10e46230898097f84d952d61'

	if [[ $1 == "synology_neon" ]]; then
		PMS_URL='https://downloads.plex.tv/plex-media-server/0.9.16.6.1993-5089475/PlexMediaServer-0.9.16.6.1993-5089475-neon-armv7.spk'
		PMS_HASH='c8959a5d1b0154087273fad06390c5e5547c0dfffac26623f48599a919f16f20'
	fi

	echo "Downloading synology package ..."
	cd $PMS_DOWNLOAD_DIR	
	curl --progress-bar -o synology.tar $PMS_URL

	local PMS_DOWNLOAD_HASH=`sha256sum synology.tar | cut -d' ' -f1`

	if [ "$PMS_HASH" != "$PMS_DOWNLOAD_HASH" ]
	then
		echo "Checksum mismatch. Downloaded file does not match this package."
		exit 1
	else
		echo "Passed checksum test."
	fi

	echo "Extracting synology.tar ..."
        tar -xOf synology.tar package.tgz | tar -xzf - -C $PMS_LIB_DIR/

	# remove not used files
	rm -r $PMS_LIB_DIR/dsm_config
	if [ -e $PMS_LIB_DIR/ld-linux.so.3 ]
	then
		rm $PMS_LIB_DIR/ld-linux.so.3
	fi
	
}


case "$1" in
    configure)
	adduser --quiet --system --shell /bin/bash --home /var/lib/plexmediaserver plex
	update-rc.d plexmediaserver defaults
	/etc/init.d/plexmediaserver stop

	# create dirs 
	mkdir -p $PMS_DOWNLOAD_DIR	
	mkdir -p $PMS_LIB_DIR

	pmsbuild=$(get_pms_build)

	if [[ $pmsbuild == "netgear" ]]; then
		install_netgear
	else
		install_synology $pmsbuild
	fi

	# remove tmp data
	cd /tmp
	rm -r $PMS_DOWNLOAD_DIR/

	#!/bin/sh

	/etc/init.d/plexmediaserver start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
