#!/bin/bash

PMS_LIB_DIR=/usr/lib/plexmediaserver
PMS_DOWNLOAD_DIR=/tmp/plex_tmp_download	

get_pms_build(){

	local cpuinfo=$(grep -i features /proc/cpuinfo)
	local cpuarch=$(grep -i architecture /proc/cpuinfo | cut -d' ' -f3 | head -n1)

	local bios_board_vendor=""
	if [[ -e /sys/class/dmi/id/board_vendor ]]; then
		bios_board_vendor=$(cat /sys/class/dmi/id/board_vendor)
	elif [[ -e /sys/devices/virtual/dmi/id/board_vendor ]]; then
		bios_board_vendor=$(cat /sys/devices/virtual/dmi/id/board_vendor)
	fi

	if [[ $bios_board_vendor == "AMD" ]]; then
		echo "synology"
	elif [[ $cpuinfo =~ .*neon.* ]] && [[ $cpuinfo =~ .*vfpv4.* ]] && [[ $cpuinfo =~ .*thumb.* ]] && [[ $cpuinfo =~ .*idiva.* ]]; then
		echo "netgear"		
	elif [[ $cpuarch == "8" ]]; then
		echo "netgear"
	else
		echo "synology"
	fi
}

install_netgear(){

	local PMS_URL='https://downloads.plex.tv/plex-media-server/1.7.6.4058-8fa494d15/plexmediaserver-ros6-binaries-annapurna_1.7.6.4058-8fa494d15_armel.deb'
	local PMS_HASH='0c1ac024a27e018cc216aac4dd898a132e4aa5923119e6374acfdd2c1225a7dc'

	echo "Downloading readynas package ..."
	cd $PMS_DOWNLOAD_DIR	
	curl --progress-bar -o readynas.deb $PMS_URL

	local PMS_DOWNLOAD_HASH=`sha256sum readynas.deb | cut -d' ' -f1`

	if [ "$PMS_HASH" != "$PMS_DOWNLOAD_HASH" ]
	then
		echo "Checksum mismatch. Downloaded file does not match this package."
		exit 1
	else
		echo "Passed checksum test."
	fi

	echo "Extracting readynas.deb ..."
        dpkg-deb --fsys-tarfile readynas.deb | tar -xf - -C $PMS_LIB_DIR/ --strip-components=4 ./apps/plexmediaserver-annapurna/Binaries

	# remove not used files
	rm $PMS_LIB_DIR/config.xml
	
}

install_synology(){

	local PMS_URL='https://downloads.plex.tv/plex-media-server/1.7.6.4058-8fa494d15/PlexMediaServer-1.7.6.4058-8fa494d15-arm7.spk'
	local PMS_HASH='f2107bd14e08b2678b99bb79eee85e3c90c595b24c6a75d0e3b820e729c5792b'

	echo "Downloading synology package ..."
	cd $PMS_DOWNLOAD_DIR	
	curl --progress-bar -o synology.tar $PMS_URL

	local PMS_DOWNLOAD_HASH=`sha256sum synology.tar | cut -d' ' -f1`

	if [ "$PMS_HASH" != "$PMS_DOWNLOAD_HASH" ]
	then
		echo "Checksum mismatch. Downloaded file does not match this package."
		exit 1
	else
		echo "Passed checksum test."
	fi

	echo "Extracting synology.tar ..."
        tar -xOf synology.tar package.tgz | tar -xzf - -C $PMS_LIB_DIR/

	# remove not used files
	rm -r $PMS_LIB_DIR/dsm_config
}


case "$1" in
    configure)
	adduser --quiet --system --shell /bin/bash --home /var/lib/plexmediaserver plex
	update-rc.d plexmediaserver defaults
	/etc/init.d/plexmediaserver stop

	# create dirs 
	mkdir -p $PMS_DOWNLOAD_DIR	
	mkdir -p $PMS_LIB_DIR

	pmsbuild=$(get_pms_build)

	if [[ $pmsbuild == "netgear" ]]; then
		install_netgear
	else
		install_synology
	fi

	# remove tmp data
	cd /tmp
	rm -r $PMS_DOWNLOAD_DIR/

	# fix web profile
	# sed -i 's/name="audio.channels" value="6"/name="audio.channels" value="2"/g' /usr/lib/plexmediaserver/Resources/Profiles/Web.xml

	# fix chromecast profile
	# sed -i 's/name="audio.channels" value="6"/name="audio.channels" value="2"/g' /usr/lib/plexmediaserver/Resources/Profiles/Chromecast.xml

	/etc/init.d/plexmediaserver start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
