#!/bin/bash

PMS_LIB_DIR=/usr/lib/plexmediaserver
PMS_DOWNLOAD_DIR=/tmp/plex_tmp_download	

get_pms_build(){

	local cpuinfo=$(grep Features /proc/cpuinfo)
	if [[ $cpuinfo =~ .*neon.* ]] && [[ $cpuinfo =~ .*vfpv4.* ]] && [[ $cpuinfo =~ .*thumb.* ]] && [[ $cpuinfo =~ .*idiva.* ]]; then
		echo "netgear"		
	else
		echo "synology"
	fi
}

install_netgear(){

	local PMS_URL='https://downloads.plex.tv/plex-media-server/1.0.1.2396-c094d0d/plexmediaserver-ros6-binaries-annapurna_1.0.1.2396-c094d0d_armel.deb'
	local PMS_HASH='2968a9da28402615d27e462ed65a96b2380b5d3a61a7fd68061dd5f28a93779c'

	echo "Downloading readynas package ..."
	cd $PMS_DOWNLOAD_DIR	
	curl --progress-bar -o readynas.deb $PMS_URL

	local PMS_DOWNLOAD_HASH=`sha256sum readynas.deb | cut -d' ' -f1`

	if [ "$PMS_HASH" != "$PMS_DOWNLOAD_HASH" ]
	then
		echo "Checksum mismatch. Downloaded file does not match this package."
		exit 1
	else
		echo "Passed checksum test."
	fi

	echo "Extracting readynas.deb ..."
        dpkg-deb --fsys-tarfile readynas.deb | tar -xf - -C $PMS_LIB_DIR/ --strip-components=4 ./apps/plexmediaserver-annapurna/Binaries

	# remove not used files
	rm $PMS_LIB_DIR/config.xml
	
}

install_synology(){

	local PMS_URL='https://downloads.plex.tv/plex-media-server/1.0.1.2396-c094d0d/PlexMediaServer-1.0.1.2396-c094d0d-arm7.spk'
	local PMS_HASH='45c9966fbad88ba2fdf975623ca36e0cf4e6addd87f68efe9ce70b2415c276c5'

	echo "Downloading synology package ..."
	cd $PMS_DOWNLOAD_DIR	
	curl --progress-bar -o synology.tar $PMS_URL

	local PMS_DOWNLOAD_HASH=`sha256sum synology.tar | cut -d' ' -f1`

	if [ "$PMS_HASH" != "$PMS_DOWNLOAD_HASH" ]
	then
		echo "Checksum mismatch. Downloaded file does not match this package."
		exit 1
	else
		echo "Passed checksum test."
	fi

	echo "Extracting synology.tar ..."
        tar -xOf synology.tar package.tgz | tar -xzf - -C $PMS_LIB_DIR/

	# remove not used files
	rm -r $PMS_LIB_DIR/dsm_config
}


case "$1" in
    configure)
	adduser --quiet --system --shell /bin/bash --home /var/lib/plexmediaserver plex
	update-rc.d plexmediaserver defaults
	/etc/init.d/plexmediaserver stop

	# create dirs 
	mkdir -p $PMS_DOWNLOAD_DIR	
	mkdir -p $PMS_LIB_DIR

	pmsbuild=$(get_pms_build)

	if [[ $pmsbuild == "netgear" ]]; then
		install_netgear
	else
		install_synology
	fi

	# remove tmp data
	cd /tmp
	rm -r $PMS_DOWNLOAD_DIR/

	# fix web profile
	sed -i 's/name="audio.channels" value="6"/name="audio.channels" value="2"/g' /usr/lib/plexmediaserver/Resources/Profiles/Web.xml

	# fix chromecast profile
	sed -i 's/name="audio.channels" value="6"/name="audio.channels" value="2"/g' /usr/lib/plexmediaserver/Resources/Profiles/Chromecast.xml

	/etc/init.d/plexmediaserver start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
