#!/bin/sh

if [ -f /proc/1/comm ] && [ "`cat /proc/1/comm`" = "systemd" ];
then
	systemctl stop plexmediaserver
	systemctl disable plexmediaserver
	/etc/init.d/plexmediaserver stop
else
	/etc/init.d/plexmediaserver stop
fi

PMS_LIB_DIR=/usr/lib/plexmediaserver

rm -rf $PMS_LIB_DIR
